version: '3'

services:
  app:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./:/srv/app:rw

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    volumes:
      # Comment out the next line in production
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/app/public:ro
    ports:
      - '80:80'

  db:
    build:
      context: .
      dockerfile: ./Dockerfile.db
    environment:
      - MYSQL_DATABASE=test_one
      - MYSQL_PASSWORD=one
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=hello
