version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/srv/app:rw

  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/app/public:ro
    ports:
      - '80:80'

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test_one
      - MYSQL_PASSWORD=one
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=hello
    volumes:
      - .docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
